### ISSUE TITLE
shows a currently playing even if playing nothing in mumble

### ISSUE THREAD

**Issue by nogweii** [Thristhart/cyrclebot-status#1]
always shows a song, even if cyrclebot in mumble isn't playing something.

![cyrclebot_status_always_show_song_bug](https://cloud.githubusercontent.com/assets/14547/6363586/5f767122-bc58-11e4-8426-9d7a6ea48d2f.png)

**Comment by thristhart** [comment]
Status page now hides the progress bar and the now playing when the cyrclebot:progress key is null.
