### ISSUE TITLE
ZOMG ERROR ERROR 502 BAD GATEWAY

### ISSUE THREAD

**Issue by nogweii** [Thristhart/cyrclebot-status#4]
Fix the server, it gives a 502 Bad Gateway.

URL: http://tom.shea.at/cyrclebot/

**Comment by thristhart** [comment]
There, I wrote a service file for it, it should stay up now.

**Comment by nogweii** [comment]
Thaaaaank you. My dota-playing habit has become just a bit easier thanks to you. :heart:
